server:
  port: 9099

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myschool?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Root5683@
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    elasticsearch:
#      client:
#        reactive:
#          # 要连接到的Elasticsearch端点的逗号分隔列表。
#          endpoints: 127.0.0.1:9300
##          username:
##          password:
#          # 连接超时时间
#          connection-timeout: 100
#      # 是否开启es仓库
#      repositories:
#        enabled: true
#      elasticsearch版本问题
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300

mybatis-plus:
  mapper-locations: classpath:/mapper/*.mapper
  type-aliases-package: top.lzmvlog.elasticsearchdemo.model

logging:
  level:
    top.lzmvlog.authority.dao: debug
  file:
    path: ./log/
